### ISSUE TITLE
Calendar year extends from December to November

### ISSUE THREAD

**Issue by Bob-Pond** [dhis2/data-quality-app-who#7]
With the Analysis tools and the Data Export for Excel tool, when I select by year and 2016 I get data for the months from December 2015 to November 2016.

**Comment by olavpo** [comment]
Unable to reproduce this.

**Comment by Bob-Pond** [comment]
Hi Olav,

 

Greetings from Jakarta where Wilfred and I (after Jorn’s departure) are supporting a DHIS2 T-o-T.

 

I had configured the Data Quality Tool on a version 2.28 instance and it was working fine.

 

Then the system was converted to 2.29 and we found that we could not configure the Tool.  The Tool is there but under Administration there is only the message that “You do not have access to change the configuration”.

 

Wilfred and I and the rest of the UiO team here all have super-user access yet we cannot get the Tool configured.

 

Suggestions?

 

Thanks and regards, Bob
